### ISSUE TITLE
部分手机提示：java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jicg** [zybieku/ZbarCode#1]
错位内容如下
java.lang.UnsatisfiedLinkError
No implementation found for java.lang.String com.dtr.zbar.build.ZBarDecoder.decodeCrop(byte[], int, int, int, int, int, int) (tried Java_com_dtr_zbar_build_ZBarDecoder_decodeCrop and Java_com_dtr_zbar_build_ZBarDecoder_decodeCrop___3BIIIIII)
com.dtr.zbar.build.ZBarDecoder.decodeCrop(Native Method)
com.znq.zbarcode.decode.DecodeHandler.decode(DecodeHandler.java:81)

这可能是什么情况导致的啊？

**Comment by zybieku** [comment]
大佬你好,native方法报错了,你是不是没有对so文件过滤,目前扫一扫只对ARM V7 V8 手机架构,所以你需要加下ndk过滤

**Comment by zybieku** [comment]
对cpu的so文件进行过滤,要删掉你不需要的.so文件包

**Comment by jicg** [comment]
嗯嗯，好的，谢谢
