### ISSUE TITLE
扫描蓝色的二维码，无法聚焦，也无法识别。怎么办

### ISSUE THREAD

**Issue by oops-iu** [zybieku/ZbarCode#2]
扫描蓝色的二维码，无法聚焦，也无法识别。怎么办

**Comment by zybieku** [comment]
@koujiao520 请问您所有手机都这样么,可以发个蓝色的二维码给我看下me.我调试一下

**Comment by oops-iu** [comment]
![img_4851](https://user-images.githubusercontent.com/32325335/31477504-e8f3c50e-af3e-11e7-8979-1664fed9e4d4.JPG)

**Comment by oops-iu** [comment]
我用的手机都扫不出来

**Comment by zybieku** [comment]
@koujiao520 你好我这边是没问题的.我测试了两台手机 华为mate8 ,还有小米5

**Comment by zybieku** [comment]
![device-2017-10-12-112656](https://user-images.githubusercontent.com/15903330/31478125-bb11b964-af40-11e7-9aa2-daa403326c85.png)

**Comment by zybieku** [comment]
@koujiao520 是不是你的手机本身相机聚焦就存在问题,大佬,麻烦您换个手机尝试一下好么

**Comment by oops-iu** [comment]
大佬，我是萌新 ， 我现在去换几个手机

**Comment by zybieku** [comment]
@koujiao520 嗯.你多换几个手机装我这个demo运行试验下,我自己特意尝试了,只不过在发票上面二维码太小,有时候识别没那么快,但是都是可以识别的.我测试你的发的这个图片是秒识别的.特别快.

**Comment by oops-iu** [comment]
qq给一下好嘛，大佬，我这边图发不出来，用的小米5，扫不出来

**Comment by zybieku** [comment]
510034906

**Comment by zybieku** [comment]
@koujiao520 你用二维码生产器,生产几个蓝色的二维码,或者换几张发票试试 我这边都没问题!

**Comment by oops-iu** [comment]
我这里没有诶，就这个一个 我这里还扫不出来
